apiVersion: apps/v1
kind: Deployment
metadata:
  name: moirai-ws
  labels:
    app: moirai-ws
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moirai-ws
  template:
    metadata:
      labels:
        app: moirai-ws
    spec:
      containers:
        - name: moirai-ws
          image: gcr.io/nlacombe-net-prod/moirai-ws:0.0.1-20190504191802
          env:
            - name: PORT
              value: "80"
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 50m
---
apiVersion: v1
kind: Service
metadata:
  name: moirai-ws
spec:
  selector:
    app: moirai-ws
  ports:
    - port: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: moirai-ws
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/frontend-entry-points: https
spec:
  rules:
    - host: moirai-api.nlacombe.net
      http:
        paths:
          - backend:
              serviceName: moirai-ws
              servicePort: 80
